SOF-47 init project
Project-Accessibility/web-portal pull request #1
Opened 2022-03-15 11:18 UTC by GewoonJaap

2022-03-17 18:59 UTC, wwessel01 approved these changes
Standaard Laravel project, is helemaal prima

2022-03-17 19:31 UTC, MartijnAmbagtsheer requested changes
Graag minimale requirements naar 8.1

2022-03-17 19:31 UTC, MartijnAmbagtsheer commented on README.md
> +- PHP 8.0 or later
8.1

2022-03-18 08:21 UTC, GewoonJaap commented on .env.example
> +APP_NAME=Laravel
Aangepast

2022-03-18 08:21 UTC, GewoonJaap commented on README.md
> +- PHP 8.0 or later
Aangepast

2022-03-18 08:25 UTC, GewoonJaap commented on composer.json
> +        "php": "^8.0.2",
Aangepast

2022-03-18 09:06 UTC, MartijnAmbagtsheer approved these changes
Aanpassingen zijn goed! :-)

2022-03-18 09:06 UTC, merged