SOF-282 Front-end configuration
Project-Accessibility/web-portal pull request #13
Opened 2022-03-26 13:58 UTC by MartijnAmbagtsheer

**Closes #SOF-282**

## Description

Styling met bootstrap is gefixt met de huisstijl van Accessibility en is minimaal WCAG AAA.

## Review focus

- Zou fijn zijn als mensen vooral even kijken naar lay-out.

## Checklist

- [x] I have run `yarn format`
- [x] I have run `php artisan test`
- [x] This PR does not add any errors to the console

A build will automatically be run by GitHub actions when any changes are made on this PR. This must complete successfully before merging.

## Screenshots or videos

<details>
<summary>Click to expand</summary>

![screencapture-dashboard-test-stylesheet-2022-03-26-14_44_20](https://user-images.githubusercontent.com/63644928/160242779-58fd5e83-d951-42a3-a800-4f2170770401.png)

</details>

2022-03-26 14:14 UTC, GewoonJaap requested changes

2022-03-26 14:14 UTC, GewoonJaap commented on resources/sass/exclude/exclude-colors.scss
> +$indigo: null;
Waarom zijn deze null gemaakt?

2022-03-26 14:14 UTC, GewoonJaap commented on resources/sass/exclude/exclude-colors.scss
> +$gray-700: nullt;
Typo? `Nullt`

2022-03-26 14:14 UTC, GewoonJaap commented on resources/views/includes/head.blade.php
> +<title>Accessibility questionnaire dashboard</title>
Misschien wat lang voor browser titel? Dashboard valt nu weg. Misschien van maken: `Questionnare | Dashboard`

2022-03-26 14:14 UTC, GewoonJaap commented on resources/views/includes/head.blade.php
> +<meta name="description" content="">
Is het de bedoeling dat de description leeg is?

2022-03-26 14:14 UTC, GewoonJaap commented on resources/views/includes/head.blade.php
> +<meta name="Saquib" content="Blade">
Wat doet deze meta tag?

2022-03-26 14:14 UTC, GewoonJaap commented on resources/js/bootstrap.js
> +var tooltipTriggerList = [].slice.call(
Kan hier geen const van gemaakt worden?

2022-03-26 14:15 UTC, MartijnAmbagtsheer commented on resources/sass/exclude/exclude-colors.scss
> +$indigo: null;
Omdat deze toch niet gebruikt worden en zo nemen ze geen ruimte in met bijv alle klassen maken zoals `bg-indigo` en `text-indigo`. Scheelt zo'n 50kb in de app.css

2022-03-26 14:15 UTC, GewoonJaap commented
Voor het vervolg misschien handig om branches als volgt te noemen: feature/sof-xxx-beschrijving
dus feature/sof-282-bootstrap
En dan voor bug fixes fix/sof-xxx-beschrijving
Is misschien wat netter

2022-03-26 14:17 UTC, GewoonJaap commented
Lijkt erop dat css/js niet goed worden gelinkt? Op de test environment werkt de styling niet. https://laravel-pr-13-gewoonjaap.cloud.okteto.net/stylesheet

2022-03-26 14:17 UTC, MartijnAmbagtsheer commented on resources/views/includes/head.blade.php
> +<meta name="Saquib" content="Blade">
Geen idee eig haha. Dit was een standaard Blade template, ik zal hem eruit halen.

2022-03-26 14:21 UTC, MartijnAmbagtsheer commented
> Lijkt erop dat css/js niet goed worden gelinkt? Op de test environment werkt de styling niet. https://laravel-pr-13-gewoonjaap.cloud.okteto.net/stylesheet Vgm komt het doordat de css/js wordt opgehaald met http:// ipv https:// en dan blocked je browser

Komt wrs omdat er geen `yarn dev` wordt gerund?

2022-03-26 14:22 UTC, GewoonJaap commented on resources/sass/exclude/exclude-colors.scss
> +$indigo: null;
Ah oke, zolang alles nog goed blijft werken dan zal t wel goed zijn :D

2022-03-29 14:02 UTC, wwessel01 approved these changes

2022-03-29 14:02 UTC, merged