Feature/sof 214 table component
Project-Accessibility/web-portal pull request #14
Opened 2022-03-29 01:26 UTC by MartijnAmbagtsheer

**Closes #SOF-214**

## Description

- Table component gemaakt
- `Readme`  aangevuld met de nodige informatie over een tabel te maken met links.

## Review focus

Er staat heel veel code in welke wellicht kan worden opgeschoond. Mocht je tips hebben: graag.

## Checklist

- [x] I have run `yarn format`
- [x] I have run `php artisan test`
- [x] This PR does not add any errors to the console

A build will automatically be run by GitHub actions when any changes are made on this PR. This must complete successfully before merging.

## Screenshots or videos

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/63644928/160513988-d94e3e63-3c41-4aa2-9b02-9ecbdcdb61b5.png)

</details>

2022-03-29 14:36 UTC, GewoonJaap commented on resources/views/stylesheet.blade.php
> +                                        <x-input type="date" name="Datum" value="2021-03-21"></x-input> <x-input type="datetime" name="Datum & tijd" value="2021-03-21T08:00"></x-input>
Waarom is de name in het nederlands terwijl de rest van de pagina engels is?

2022-03-29 14:44 UTC, GewoonJaap commented
![Schermafbeelding 2022-03-29 om 16 43 41](https://user-images.githubusercontent.com/33700526/160638204-875ac52d-0ceb-4e77-b54a-39939e14b2f9.png)
Alle fake-routes lijken niet te werken

2022-03-29 14:44 UTC, GewoonJaap commented on routes/web.php
> +  Route::get('/fake-route')->name('fake.route.without.params');
Ik zou dit aanpassen naar /testing/table of iets in die geest, fake-route is beetje vreemd in mijn ogen

2022-03-29 16:35 UTC, MartijnAmbagtsheer commented on resources/views/stylesheet.blade.php
> +                                <x-button type="remove">Verwijderen</x-button>
Ja qua code, maar dit is visueel. Neem aan dat we voor Accessibility straks ook de front-end weergeven in het Nederlands haha. Maar ik ga alles gelijktrekken :-)

2022-03-30 06:29 UTC, IntissarJ requested changes
Alles ziet er voor de rest goed uit, view components ziet er ook goed uit. Alleen die questiontype

2022-03-30 06:29 UTC, IntissarJ commented on app/Enums/QuestionOptionType.php
>  enum QuestionOptionType: string
mist "SCALE/RANGE" vraagtype

2022-03-30 06:37 UTC, IntissarJ commented
Was het ook niet de bedoeling dat een table row clickable zou moeten zijn voor de details pagina van die table gegevens?

2022-03-30 06:37 UTC, IntissarJ commented on app/Enums/QuestionOptionType.php
>  enum QuestionOptionType: string
bedenk me net dat het niet voor deze pr bedoeld is

2022-03-30 15:23 UTC, GewoonJaap commented
Moet er trouwens ook nog paginering worden toegevoegd? Kan me herinneren dat ik dat ergens in Jira gezet had als subtaak, dacht bij deze story maar kan m niet meer vinden. Waar die nu wel staat is mij een vraag 😂

2022-03-30 18:22 UTC, MartijnAmbagtsheer commented
> Moet er trouwens ook nog paginering worden toegevoegd? Kan me herinneren dat ik dat ergens in Jira gezet had als subtaak, dacht bij deze story maar kan m niet meer vinden. Waar die nu wel staat is mij een vraag 😂

@GewoonJaap nee pagination is nu nog niet nodig.

2022-03-30 19:10 UTC, GewoonJaap approved these changes

2022-03-30 19:17 UTC, IntissarJ approved these changes

2022-03-30 19:17 UTC, merged