Feature/sof 91/92/253/93/95 onderzoek crud
Project-Accessibility/web-portal pull request #17
Opened 2022-03-31 02:27 UTC by milovdpas

**Closes #XX**

## Description

Dit is het CRUD van de onderzoek

## Review focus

Focus vooral op of alle schermen werken en of de flow het goed doet.

## Checklist

- [ ] I have run `yarn format`
- [ ] I have run `php artisan test`
- [ ] This PR does not add any errors to the console

A build will automatically be run by GitHub actions when any changes are made on this PR. This must complete successfully before merging.

## Screenshots or videos

<details>
<summary>Click to expand</summary>

</details>

2022-04-02 10:24 UTC, GewoonJaap requested changes
![afbeelding](https://user-images.githubusercontent.com/33700526/161378970-270a1ebf-a444-4e06-8542-65f97eb82edb.png)

Klopt het dat de image upload en de drag en drop box aan elkaar gekoppeld zijn? Kan maar 1 file drag en droppen en die verschijnt dan ook automatisch bij t image input veld

2022-04-03 00:28 UTC, MartijnAmbagtsheer commented
> ![afbeelding](https://user-images.githubusercontent.com/33700526/161378970-270a1ebf-a444-4e06-8542-65f97eb82edb.png)
> 
> Klopt het dat de image upload en de drag en drop box aan elkaar gekoppeld zijn? Kan maar 1 file drag en droppen en die verschijnt dan ook automatisch bij t image input veld

@GewoonJaap ik heb het niet gemaakt, maar zo ziet het er wel uit.

2022-04-03 00:28 UTC, MartijnAmbagtsheer approved these changes

2022-04-03 23:18 UTC, milovdpas commented
> ![afbeelding](https://user-images.githubusercontent.com/33700526/161378970-270a1ebf-a444-4e06-8542-65f97eb82edb.png)
> 
> Klopt het dat de image upload en de drag en drop box aan elkaar gekoppeld zijn? Kan maar 1 file drag en droppen en die verschijnt dan ook automatisch bij t image input veld

Deze zijn inderdaad aan elkaar gekoppeld.

2022-04-04 07:20 UTC, GewoonJaap approved these changes

2022-04-04 07:20 UTC, merged