SOF-201 Dashboard API
Project-Accessibility/web-portal pull request #18
Opened 2022-04-03 00:08 UTC by MartijnAmbagtsheer

**Closes #SOF-201**

## Description

- Dynamic API

## Checklist

- [x] I have run `yarn format`
- [x] I have run `php artisan test`
- [x] This PR does not add any errors to the console

A build will automatically be run by GitHub actions when any changes are made on this PR. This must complete successfully before merging.

2022-04-03 08:13 UTC, GewoonJaap requested changes
Om heel eerlijk te zijn, denk ik niet dat dit handig is om een API op te zetten.
* Je kan op dit moment elk model benaderen dat je wilt, iets wat je echt niet moet willen. (Een random gebruiker kan nu bijvoorbeeld de users tabel ophalen en de gegevens van veron/aafke in zien, het is nu mogelijk om de hele participants tabel op te halen waardoor je voor andere mensen hun vragenlijst kunt gaan invullen)
* Als ik nu een vragenlijst wil ophalen bij code, moet ik een Laravel query gaan meegeven vanuit de front-end, iets wat niet heel handig is.

Ik zou gewoon werken met losse API controllers, waarschijnlijk hebben we er maar 1/2 nodig? Vragenlijst ophalen en opsturen? Dit is veel veiliger (AVG), maar maakt het ook veel beter onderhoudbaar. Het is nu namelijk niet mogelijk om custom logica per endpoint te implementeren.
En als ik een vragenlijst wil ophalen waarvoor ik ben uitgenodigd wil je eigenlijk zo iets aanroepen: `questionnaire/{{id}}` waar het ID je unieke code is die je gekregen hebt.

Eventueel kan hiervoor een interface gemaakt worden die gebruikt kan worden voor de standaard functies? Maar weet niet wat handig is tbh. Maar dit lijkt mij niet handig in gebruik

2022-04-03 23:35 UTC, milovdpas commented on database/factories/ParticipantFactory.php
> +            'code' => $this->faker->unique()->md5,
Ik snap waarom je dit doet, hier kunnen we alleen niet mee testen aangezien niet weten wat er gehasht is.

2022-04-03 23:50 UTC, milovdpas requested changes

2022-04-03 23:50 UTC, milovdpas commented on routes/api.php
> +        Route::get('/questions/{id}', [QuestionController::class, 'get']);
add answer endpoint toevoegen (Logica hiervan hoeft hiervoor natuurlijk nog niet geschreven te worden).
closeQuestionaire endpoint toevoegen, deze is voor als de participant zijn vragenlijst opstuurt en definitief afsluit.

2022-04-03 23:51 UTC, milovdpas commented on README.md
> +De tweede route krijg je één model terug op basis van het `id`.
Dit is zo te zien al aangepast aan de hand van de feedback van Jaap

2022-04-04 07:19 UTC, GewoonJaap commented on database/factories/ParticipantFactory.php
> +            'code' => $this->faker->unique()->md5,
Het idee van de md5 was eigenlijk om een random code te genereren voor de seeddata

2022-04-04 15:02 UTC, GewoonJaap approved these changes

2022-04-04 17:15 UTC, MartijnAmbagtsheer commented on database/factories/ParticipantFactory.php
> +            'code' => $this->faker->unique()->md5,
@milovdpas maakt het uit voor seed data?

2022-04-04 19:47 UTC, milovdpas requested changes

2022-04-04 19:47 UTC, milovdpas commented on README.md
> +    | /questions/{question}/{code}    | GET     | question: het ID van de vragenlijst   | Een vraag met daarbij de antwoordmogelijkheden en gegeven antwoorden door de participant |
Als het de ID van de vragenlijst is, dan moet de parameter questionnaire heten toch? Voorstel /questionnaires/{code}/questions. Zo niet dan moet de beschrijving zijn het ID van de vraag._

2022-04-04 19:56 UTC, MartijnAmbagtsheer commented on README.md
> +    | /questions/{question}/{code}    | GET     | question: het ID van de vragenlijst   | Een vraag met daarbij de antwoordmogelijkheden en gegeven antwoorden door de participant |
Oh foutje idd. Ik pas het aan.

2022-04-05 11:19 UTC, milovdpas approved these changes

2022-04-05 11:20 UTC, merged