SOF-68 SOF-69 SOF-96 SOF-98 SOF-263 - Questionnaires CRUD
Project-Accessibility/web-portal pull request #21
Opened 2022-04-05 23:25 UTC by MartijnAmbagtsheer

**Closes #SOF-68 #SOF-69 #SOF-96 #SOF-98 #SOF-263**

## Description

- Questionnaires CRUD
- Nodige aanpassingen in de routes en andere bestanden
- Wat bugs opgelost mbt de componenten
- 
## Checklist

- [x] I have run `yarn format`
- [x] I have run `php artisan test`
- [x] This PR does not add any errors to the console

A build will automatically be run by GitHub actions when any changes are made on this PR. This must complete successfully before merging.

2022-04-05 23:29 UTC, MartijnAmbagtsheer commented on resources/views/admin/research/create.blade.php
> +            <x-input required="0" type="textarea" label="Omschrijving" name="description"
Mocht je denken hoezo `0`?

"false" werkt niet...

2022-04-06 13:49 UTC, milovdpas requested changes
Routing opschonen en model binding toevoegen

2022-04-06 13:49 UTC, milovdpas commented on app/Http/Controllers/QuestionnaireController.php
> +        )->with('success', 'De vraag is verwijderd!');
De vragenlijst

2022-04-06 13:49 UTC, milovdpas commented on app/Http/Controllers/QuestionnaireController.php
> +    public function archive(Research $research)
Questionnaire class ook nog toevoegen

2022-04-06 13:49 UTC, milovdpas commented on app/Http/Controllers/QuestionnaireController.php
> +    public function archives()
Research class toevoegen

2022-04-06 13:49 UTC, milovdpas commented on app/Http/Controllers/QuestionnaireController.php
> +    public function restore(Research $research)
Questionnaire class ook nog toevoegen

2022-04-06 13:49 UTC, milovdpas commented on app/Http/Controllers/QuestionnaireController.php
> +    public function deletes()
Research class ook nog toevoegen

2022-04-06 13:55 UTC, GewoonJaap requested changes
Lijkt erop dat de 404 pagina's nu naar `/researches` gaan?
![afbeelding](https://user-images.githubusercontent.com/33700526/161991059-68948bdb-513e-44ce-b5dd-9638594828ae.png)
* Kleine letter a bij `acties`
* Klopt het dat de `Er zijn nog geen items. ` balk niet volledig doorloopt?

2022-04-06 13:55 UTC, GewoonJaap commented
Font ontbreekt trouwens ook nog steeds :/

2022-04-06 17:40 UTC, GewoonJaap commented on resources/views/admin/research/create.blade.php
> +            <x-input required="0" type="textarea" label="Omschrijving" name="description"
Kan je de required tag dan trouwens niet gewoon eruit halen? Want vgm hoef je required alleen te zetten als t echt required is

2022-04-06 20:20 UTC, MartijnAmbagtsheer commented on resources/views/admin/research/create.blade.php
> +            <x-input required="0" type="textarea" label="Omschrijving" name="description"
Ik kan het idd ook omdraaien.

2022-04-06 22:39 UTC, milovdpas requested changes
Functionaliteiten werken goed, routing is alleen nog niet netjes.

2022-04-06 22:39 UTC, milovdpas commented on routes/web.php
> +                        ->defaults('display', 'aanpassen');
Dit mag in de prefix

2022-04-06 22:39 UTC, milovdpas commented on routes/web.php
> +                    );
Dit mag in de prefix

2022-04-06 22:39 UTC, milovdpas commented on routes/web.php
> +                        ->defaults('display', 'Vragenlijsten');
Mooier als je hiervoor een methode maakt in je controller

2022-04-07 06:55 UTC, GewoonJaap commented
404 lijkt nog steeds naar `/researches` te leiden

2022-04-07 08:27 UTC, MartijnAmbagtsheer commented
> 404 lijkt nog steeds naar `/researches` te leiden (Als je gewoon wat random meuk in de url gooit, bv: `https://laravel-pr-21-gewoonjaap.cloud.okteto.net/rdasdasdajk`)

Klopt. Omdat de homepagina nog niet is zoals we willen en de 404 pagina ook niet leek dit mij een goede tussenstap om eventuele fouten te voorkomen

2022-04-07 09:11 UTC, GewoonJaap approved these changes

2022-04-07 11:25 UTC, milovdpas approved these changes

2022-04-07 11:25 UTC, merged