Feature/sof 99 sections
Project-Accessibility/web-portal pull request #22
Opened 2022-04-06 13:29 UTC by milovdpas

**Closes #XX**

## Description

CRUD Sections

## Review focus

Concentrate on that the flow is good and all CRUD operations work

A build will automatically be run by GitHub actions when any changes are made on this PR. This must complete successfully before merging.

2022-04-06 22:40 UTC, MartijnAmbagtsheer requested changes

2022-04-06 22:40 UTC, MartijnAmbagtsheer commented on resources/views/admin/section/edit.blade.php
> +            <x-input required="0" type="textarea" label="Omschrijving" name="description"
Dit heb ik nu aangepast in mijn PR

Voorheen: niet required fields krijgen `required="0"`
**nu**: required fields krijgen `required` (meer is niet nodig)

2022-04-07 08:03 UTC, wwessel01 reviewed
![image](https://user-images.githubusercontent.com/49717888/162150638-c1212874-aa1e-4240-a840-50fe6133d985.png)
Wat moet het vak aan de rechterkant voorstellen? In de okteto omgeving lijkt deze leeg te zijn.
Zelfde voor details pagina, hier is ook een wit vlak

2022-04-07 09:37 UTC, MartijnAmbagtsheer requested changes
![image](https://user-images.githubusercontent.com/63644928/162169592-529b1eb7-d48c-4c78-b32f-1b917b68ccf6.png)

Achter geofence zou ik graag iets van 'm' of 'meter ' zien staan, dat is voor ons misschien duidelijk, maar voor Veron wellicht niet.

2022-04-07 12:20 UTC, milovdpas commented
> ![image](https://user-images.githubusercontent.com/49717888/162150638-c1212874-aa1e-4240-a840-50fe6133d985.png) Wat moet het vak aan de rechterkant voorstellen? In de okteto omgeving lijkt deze leeg te zijn. Zelfde voor details pagina, hier is ook een wit vlak

Klopt moet nog een API KEY in de .env variabele worden toegevoegd in okteto

2022-04-09 08:16 UTC, GewoonJaap commented
* Ik mis eigenlijk nog de teachablemachine class name bij de onderdelen. Zodat er kan bepaald worden welk onderdeel in de buurt is.
* Bij het maken van een vragenlijst staat er `Locatie foto's`, ik zou dit aanpassen naar TeachableMachine model of iets in die geest, dadelijk gaan ze een imgur linkje toevoegen met de foto's

2022-04-09 08:30 UTC, GewoonJaap commented
De fotos link lijkt niet te werken als je erop klikt, omdat deze doorverwijst naar /rowe.net

2022-04-10 20:51 UTC, MartijnAmbagtsheer approved these changes

2022-04-11 00:01 UTC, MartijnAmbagtsheer commented
> * Bij het maken van een vragenlijst staat er `Locatie foto's`, ik zou dit aanpassen naar TeachableMachine model of iets in die geest, dadelijk gaan ze een imgur linkje toevoegen met de foto's

@GewoonJaap Dat hoort niet in de MR/PR. Ik maak er een kaartje voor aan

2022-04-11 00:55 UTC, milovdpas commented
> 

- Ik vond dit nog niet nodig om toe te voegen aangezien dat meer bij de user story van de teachable machine hoort.
- Dit is niet van deze feature, maar ik zal het wel aanpassen in deze pull request

2022-04-11 01:09 UTC, milovdpas commented
> De fotos link lijkt niet te werken als je erop klikt, omdat deze doorverwijst naar /rowe.net

Welke foto's link?

2022-04-11 07:36 UTC, GewoonJaap commented
> * gen aangezien dat meer bij de user story van de teachable machine hoort.
> 
> * Dit is niet van deze feature, maar ik zal het wel aanpassen in deze pull request

Ah oke, snap ik

2022-04-11 07:38 UTC, GewoonJaap commented
> > De fotos link lijkt niet te werken als je erop klikt, omdat deze doorverwijst naar /rowe.net
> 
> Welke foto's link?

![afbeelding](https://user-images.githubusercontent.com/33700526/162687838-512e5c97-310e-4ab6-89a1-15c59725f0c9.png)
Deze bedoelde ik, als je hierop klikt ga je naar https://laravel-pr-22-gewoonjaap.cloud.okteto.net/researches/1/questionnaires/oreilly.com

2022-04-11 10:35 UTC, milovdpas commented
> > > De fotos link lijkt niet te werken als je erop klikt, omdat deze doorverwijst naar /rowe.net
> > 
> > 
> > Welke foto's link?
> 
> ![afbeelding](https://user-images.githubusercontent.com/33700526/162687838-512e5c97-310e-4ab6-89a1-15c59725f0c9.png) Deze bedoelde ik, als je hierop klikt ga je naar https://laravel-pr-22-gewoonjaap.cloud.okteto.net/researches/1/questionnaires/oreilly.com

Aah oke, ja nogmaals dat is niet mijn pull request, dit is van de questionaire CRUD

2022-04-11 12:01 UTC, wwessel01 approved these changes

2022-04-11 12:03 UTC, GewoonJaap approved these changes

2022-04-13 09:36 UTC, merged