SOF-326 Login
Project-Accessibility/web-portal pull request #24
Opened 2022-04-13 07:49 UTC by MartijnAmbagtsheer

**Closes #SOF-326**

## Description

Login and auth functionality.

## Checklist

- [x] I have run `yarn format`
- [x] I have run `php artisan test`
- [x] This PR does not add any errors to the console

A build will automatically be run by GitHub actions when any changes are made on this PR. This must complete successfully before merging.

## Screenshots or videos

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/63644928/163126658-815b0ef8-5478-4c70-a298-00512138ee9d.png)
![image](https://user-images.githubusercontent.com/63644928/163126713-08d73d84-e6bf-46b4-8f36-de4e0cc6040c.png)
![image](https://user-images.githubusercontent.com/63644928/163126783-021ab5da-f508-440e-b05e-a6404df5d5dc.png)

</details>

2022-04-13 08:11 UTC, GewoonJaap requested changes
Kan niet inloggen op de okteto omgeving:
![afbeelding](https://user-images.githubusercontent.com/33700526/163130937-491c44d5-111a-40e1-a54c-5d3ff6c4a16b.png)

info@accessibility.nl:admin gebruikt

2022-04-13 08:11 UTC, GewoonJaap commented on app/Exceptions/Handler.php
> +                ->redirectTo('/login')
Kan je hier niet een route meegeven?

2022-04-13 08:11 UTC, GewoonJaap commented on app/Http/Kernel.php
> +            // Illuminate\Session\Middleware\AuthenticateSession::class,
Kan dit weg, omdat t toch uitgecomment is?

2022-04-13 08:11 UTC, GewoonJaap commented on app/Http/Requests/Auth/LoginRequest.php
> +    #[ArrayShape(['email' => 'string[]', 'password' => 'string[]'])]
Wat doet dit?

2022-04-13 08:11 UTC, GewoonJaap commented on database/seeders/DatabaseSeeder.php
> +                '$2y$10$.hq3lePFqgfTr5UBK1kOmecCm2rnC7SAosaVAxQ9qm5OHk/Rmf72e',
Zou ik aanpassen naar bcrypt functie. Als ik rond kijk op GitHub zie ik ook nergens een seeder waar de hash hardcoded in staat, maken allemaal gebruik van bcrypt functie. Zo staat het ook beschreven op de Laravel documentatie (https://laravel.com/docs/9.x/seeding)

2022-04-13 08:11 UTC, GewoonJaap commented on tests/Feature/Auth/AuthenticationTest.php
> +        $response = $this->get('/login');
Kan hier niet een route naam gebruikt worden?

2022-04-13 08:11 UTC, GewoonJaap commented on tests/Feature/Auth/AuthenticationTest.php
> +        $response = $this->post('/login', [
Route naam gebruiken?

2022-04-13 08:11 UTC, GewoonJaap commented on tests/Feature/Auth/AuthenticationTest.php
> +        $this->post('/login', [
Route naam?

2022-04-13 11:25 UTC, MartijnAmbagtsheer commented on app/Http/Requests/Auth/LoginRequest.php
> +    #[ArrayShape(['email' => 'string[]', 'password' => 'string[]'])]
Is in principe een IDE helper om zo exact te weten wat voor soort array je ophaalt.

2022-04-13 11:36 UTC, GewoonJaap requested changes
![afbeelding](https://user-images.githubusercontent.com/33700526/163171765-913fed9a-a676-4c97-aa45-824639668217.png)
Wanneer je hovert op logout is er een witte achtergrond, en deze staat nu helemaal links ipv rechts op de nav bar

2022-04-14 12:21 UTC, wwessel01 approved these changes

2022-04-17 14:17 UTC, GewoonJaap approved these changes

2022-04-17 14:17 UTC, merged