SOF-107 SOF-108 SOF-109 SOF-110 Question types
Project-Accessibility/web-portal pull request #28
Opened 2022-04-18 00:45 UTC by MartijnAmbagtsheer

**Closes #SOF-107 #SOF-108 #SOF-109 #SOF-110**

## Description

- Question types in the create and edit.
- Viewing the question types on the details page.

## Checklist

- [x] I have run `yarn format`
- [x] I have run `php artisan test`
- [x] This PR does not add any errors to the console

A build will automatically be run by GitHub actions when any changes are made on this PR. This must complete successfully before merging.

## Screenshots or videos

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/63644928/163738344-8f51d924-ea68-4e84-982a-c6f52a98a6ff.png)
![image](https://user-images.githubusercontent.com/63644928/163738447-322adfff-274f-4735-b61e-da2c9698aa3f.png)

</details>

2022-04-18 00:49 UTC, MartijnAmbagtsheer commented on resources/views/admin/question/edit.blade.php
> +        @php
Dit kan efficienter, maar is voor nu niet belangrijk. Ik maak er een kaartje voor aan.

2022-04-18 08:00 UTC, GewoonJaap requested changes

2022-04-18 08:00 UTC, GewoonJaap commented on storage/framework/sessions/sxoPiNDYV27hiNhnWS6oHXVuCnQ8LK2olihtySN2
> +a:3:{s:6:"_token";s:40:"6mPs0q5M0XL0KD8Ff43R94UFSwCkwz4rm9sc1Lnr";s:9:"_previous";a:1:{s:3:"url";s:79:"http://dashboard.test/researches/1/questionnaires/1/sections/1/questions/2/edit";}s:6:"_flash";a
gitignore?

2022-04-18 08:00 UTC, GewoonJaap commented on resources/views/question-types.blade.php
> +                <source src="{{ asset('storage/upload/files/audio/20220411_62538caeb6572.mp3') }}" type="audio/mpeg">
Werkt dit? Want lijkt mij dat deze file alleen lokaal op jouw PC staat

2022-04-18 08:00 UTC, GewoonJaap commented on resources/views/admin/question/edit.blade.php
> +        if (!{{empty(old('multipleChoice')) ? 1 : 0}}) {
Gok dat dit niet te stylen is omdat prettier er overheen walst?

2022-04-18 08:00 UTC, GewoonJaap commented on resources/views/admin/question/edit.blade.php
> +                    case \App\Enums\QuestionOptionType::MULTIPLE_CHOICE:
Imports

2022-04-18 08:00 UTC, GewoonJaap commented on resources/views/admin/question/details.blade.php
> +                                        <strong>{{ __('question-types.'. $key) }}</strong>
Wat doet deze underscore eigenlijk?

2022-04-18 08:00 UTC, GewoonJaap commented on resources/sass/app.scss
> +    text-decoration:none;
Spatie na de `:`

2022-04-18 08:01 UTC, GewoonJaap commented
`yarn prod` faalt overigens,

``#16 13.13 ERROR in ./resources/css/app.css#16 13.13 Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):#16 13.13 ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):#16 13.13 SyntaxError#16 13.13#16 13.13 (16:1) /app/resources/css/app.css Unclosed block#16 13.13#16 13.13   14 | }#16 13.13   15 |#16 13.13 > 16 | .accordion-button:disabled::after {#16 13.13      | ^#16 13.13   17 |     background: none;#16 13.13   18 |#16 13.13#16 13.13     at processResult (/app/node_modules/webpack/lib/NormalModule.js:758:19)#16 13.13     at /app/node_modules/webpack/lib/NormalModule.js:860:5#16 13.13     at /app/node_modules/loader-runner/lib/LoaderRunner.js:399:11#16 13.13     at /app/node_modules/loader-runner/lib/LoaderRunner.js:251:18#16 13.13     at context.callback (/app/node_modules/loader-runner/lib/LoaderRunner.js:124:13)#16 13.13     at Object.loader (/app/node_modules/postcss-loader/dist/index.js:140:7)#16 13.13#16 13.13 1 ERROR in child compilations (Use 'stats.children: true' resp. '--stats-children' for more details)#16 13.13 webpack compiled with 2 errors``

2022-04-18 15:15 UTC, milovanderpas commented on resources/views/admin/question/edit.blade.php
> +                    case \App\Enums\QuestionOptionType::MULTIPLE_CHOICE:
Dit is blade, kun je niet zomaar imports gebruiken

2022-04-18 15:15 UTC, milovanderpas commented on resources/views/admin/question/details.blade.php
> +                                        <strong>{{ __('question-types.'. $key) }}</strong>
Dit is voor translatie, stel je gaat meerdere talen implementeren als ik het mij goed herinner

2022-04-18 15:18 UTC, milovanderpas commented on resources/views/question-types.blade.php
> +                <source src="{{ asset('storage/upload/files/audio/20220411_62538caeb6572.mp3') }}" type="audio/mpeg">
De git ignore zorgt ervoor dat de files niet op de github komen te staan
![image](https://user-images.githubusercontent.com/89784290/163830238-e57ec6d0-2377-4a47-bc73-9a3b1aaad78a.png)

2022-04-18 15:48 UTC, milovdpas commented on resources/sass/app.scss
> +    text-decoration:none;
fixed

2022-04-18 15:49 UTC, milovdpas commented on resources/views/admin/question/edit.blade.php
> +        if (!{{empty(old('multipleChoice')) ? 1 : 0}}) {
Prettier laat dat idd niet toe.

2022-04-18 15:51 UTC, milovdpas commented on storage/framework/sessions/sxoPiNDYV27hiNhnWS6oHXVuCnQ8LK2olihtySN2
> +a:3:{s:6:"_token";s:40:"6mPs0q5M0XL0KD8Ff43R94UFSwCkwz4rm9sc1Lnr";s:9:"_previous";a:1:{s:3:"url";s:79:"http://dashboard.test/researches/1/questionnaires/1/sections/1/questions/2/edit";}s:6:"_flash";a
Bij mij worden de sessions automatisch geignored
![image](https://user-images.githubusercontent.com/63716517/163834971-60feca25-6707-4e8a-8427-227b2a863a3d.png)

2022-04-18 15:52 UTC, milovdpas commented
> `yarn prod` faalt overigens,
> 
> `#16 13.13 ERROR in ./resources/css/app.css#16 13.13 Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):#16 13.13 ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):#16 13.13 SyntaxError#16 13.13#16 13.13 (16:1) /app/resources/css/app.css Unclosed block#16 13.13#16 13.13 14 | }#16 13.13 15 |#16 13.13 > 16 | .accordion-button:disabled::after {#16 13.13 | ^#16 13.13 17 | background: none;#16 13.13 18 |#16 13.13#16 13.13 at processResult (/app/node_modules/webpack/lib/NormalModule.js:758:19)#16 13.13 at /app/node_modules/webpack/lib/NormalModule.js:860:5#16 13.13 at /app/node_modules/loader-runner/lib/LoaderRunner.js:399:11#16 13.13 at /app/node_modules/loader-runner/lib/LoaderRunner.js:251:18#16 13.13 at context.callback (/app/node_modules/loader-runner/lib/LoaderRunner.js:124:13)#16 13.13 at Object.loader (/app/node_modules/postcss-loader/dist/index.js:140:7)#16 13.13#16 13.13 1 ERROR in child compilations (Use 'stats.children: true' resp. '--stats-children' for more details)#16 13.13 webpack compiled with 2 errors`

Klopt fout zat in de app.scss, er werdt een bracket niet gesloten

2022-04-18 15:55 UTC, milovdpas commented on storage/framework/sessions/sxoPiNDYV27hiNhnWS6oHXVuCnQ8LK2olihtySN2
> +a:3:{s:6:"_token";s:40:"6mPs0q5M0XL0KD8Ff43R94UFSwCkwz4rm9sc1Lnr";s:9:"_previous";a:1:{s:3:"url";s:79:"http://dashboard.test/researches/1/questionnaires/1/sections/1/questions/2/edit";}s:6:"_flash";a
Ik zie nu wel dat er veel gitignores zijn verwijderd, @MartijnAmbagtsheer Weet jij hier iets vanaf?

2022-04-18 16:16 UTC, milovdpas requested changes
![image](https://user-images.githubusercontent.com/63716517/163838153-a727570b-0782-4d63-8f77-021a0028d92d.png)
Placeholder tekst tonen als er geen mogelijkheden zijn geselecteerd. Iets van "Geen mogelijkheden geselecteerd."

2022-04-18 21:51 UTC, MartijnAmbagtsheer commented on resources/views/admin/question/details.blade.php
> +                                        <strong>{{ __('question-types.'. $key) }}</strong>
Gaat er vooral om dat de namen van die question types niet overal door de code heen verspreid staan.

2022-04-19 07:46 UTC, GewoonJaap commented on resources/views/question-types.blade.php
> +                <source src="{{ asset('storage/upload/files/audio/20220411_62538caeb6572.mp3') }}" type="audio/mpeg">
Ja snap ik, alleen als dit op dev/acc komt werkt deze audio source niet, dus zou dit vervangen door een .mp3 link die t daar wel doet ;)

2022-04-19 07:49 UTC, GewoonJaap commented
Misschien idee om ook meteen seeders toe te voegen voor de vragen? Daar wordt op dit moment nog niks geseed namelijk

2022-04-19 10:52 UTC, GewoonJaap commented on resources/views/question-types.blade.php
> +                <source src="{{ asset('storage/upload/files/audio/20220411_62538caeb6572.mp3') }}" type="audio/mpeg">
jaap.su/winnerdinner.mp3

2022-04-19 10:52 UTC, GewoonJaap commented on resources/views/question-types.blade.php
> +                <source src="{{ asset('storage/upload/files/audio/20220411_62538caeb6572.mp3') }}" type="audio/mpeg">
https://jaap.su/youLost.mp3

2022-04-19 12:36 UTC, wwessel01 commented on resources/views/admin/question/create.blade.php
> +                        <div class="col-md-2 mt-1 px-0 me-3" style="width: 40px!important;">
Inline styling?

2022-04-19 12:36 UTC, wwessel01 commented on resources/views/admin/question/edit.blade.php
> +                                        <div class="col-md-2 mt-1 px-0 me-3" style="width: 40px!important;">
Hier nogmaals inline styling?

2022-04-20 09:31 UTC, GewoonJaap commented on database/seeders/DatabaseSeeder.php
> +    //    private function createNemoEntranceQuestions(Section $section)
Kan dit niet weg? Nu het toch uitgecomment is?

2022-04-20 21:59 UTC, MartijnAmbagtsheer commented on database/seeders/DatabaseSeeder.php
> +    //    private function createNemoEntranceQuestions(Section $section)
Is nu opgelost door uitbreiden seeder.

2022-04-21 07:03 UTC, GewoonJaap approved these changes

2022-04-21 13:43 UTC, milovdpas approved these changes

2022-04-21 13:43 UTC, merged