Feature/database
Project-Accessibility/web-portal pull request #3
Opened 2022-03-21 10:31 UTC by milovdpas

**Closes #XX**

## Description

Made database setup

## Review focus

Concentrate on models and migrations

## Checklist

- migrations runnen

A build will automatically be run by GitHub actions when any changes are made on this PR. This must complete successfully before merging.

2022-03-21 10:34 UTC, GewoonJaap requested changes
package-lock.json kan eruit gezien we yarn gebruiken ;)

2022-03-21 10:34 UTC, GewoonJaap commented on .env.example
> +APP_NAME=Accessibility_Questionnaire_Dashboard
Deze had ik aangepast in mijn GH actions PR, Je moet " voor en achter die app name string gooien dan doet ie het

2022-03-21 10:34 UTC, GewoonJaap commented on README.md
> +- Run `npm install` to install yarn.
? Nu wordt yarn niet geinstalleerd

2022-03-21 10:34 UTC, GewoonJaap commented on package.json
> +        "yarn": "^1.22.18"
Yarn is geen dependency van het project, maar een globale, kan dus weg hier

2022-03-21 10:36 UTC, milovdpas commented on README.md
> +- Run `npm install` to install yarn.
Jawel kijk maar in package.json

2022-03-21 10:38 UTC, MartijnAmbagtsheer commented on README.md
> +- Run `npm install` to install yarn.
Dan gaat hij de packages via Node installeren. Yarn is sneller

2022-03-21 10:53 UTC, MartijnAmbagtsheer requested changes
PHP naar 8.1 zetten (in Xampp nieuwe PHP installeren, is heel simpel en je phpstorm updaten naar de laatste versie zodat deze ook 8.1 heeft. Dit gaat het makkelijkste via de Toolbox van JetBrains.

2022-03-21 10:53 UTC, MartijnAmbagtsheer commented on app/Models/Answer.php
> +
Alles wat je niet gebruikt graag eruit halen. Maakt de code een stuk schoner en leesbaarder

2022-03-21 10:53 UTC, MartijnAmbagtsheer commented on app/Models/Answer.php
> +
Alles wat geen string is casten. Werkt een stuk soepeler als dat je dat achteraf moet doen

2022-03-21 10:53 UTC, MartijnAmbagtsheer commented on app/Models/Geofence.php
> +
Alles wat je niet gebruikt graag eruit halen. Maakt de code een stuk schoner en leesbaarder

2022-03-21 10:53 UTC, MartijnAmbagtsheer commented on app/Models/Participant.php
> +        return $this->belongsTo(Questionnaire::class)->first();
Het is een 1-to-1 relatie, hoef je geen `->first()` te doen

Docs: https://laravel.com/docs/9.x/eloquent-relationships#one-to-one

2022-03-21 10:53 UTC, MartijnAmbagtsheer commented on app/Models/Question.php
> +
Alles wat je niet gebruikt graag eruit halen. Maakt de code een stuk schoner en leesbaarder

2022-03-21 10:53 UTC, MartijnAmbagtsheer commented on app/Models/QuestionOption.php
> +        return $this->belongsTo(Question::class)->first();
https://laravel.com/docs/9.x/eloquent-relationships#one-to-one

2022-03-21 10:53 UTC, MartijnAmbagtsheer commented on composer.json
> +        "php": "^8.0",
8.1 aub (wegens het gebruik van constants wat ons wel kan helpen)

2022-03-21 10:53 UTC, MartijnAmbagtsheer commented on database/migrations/2022_03_21_092204_create_geofences_table.php
> +            $table->double("radius");
Aan een float hebben we genoeg qua precision
https://www.educative.io/edpresso/what-is-the-difference-between-float-and-double

2022-03-21 10:53 UTC, MartijnAmbagtsheer commented on webpack.mix.js
> +    .postCss('resources/css/app.scss', 'public/css', [
Dit hoort niet bij de database MR. Voor nu prima, volgende MR's rekening mee houden dat je bepaalde dingen gescheiden houdt.

2022-03-21 12:17 UTC, milovdpas commented on app/Models/QuestionOption.php
> +        return $this->belongsTo(Question::class)->first();
one to many

2022-03-21 12:36 UTC, milovdpas commented on webpack.mix.js
> +    .postCss('resources/css/app.scss', 'public/css', [
Is goed

2022-03-21 15:33 UTC, MartijnAmbagtsheer commented on app/Models/Answer.php
> +  protected $fillable = ['participant_id', 'question_option_id', 'answer'];
@GewoonJaap ik hoorde van Milo dat Prettier deze naast elkaar zet inplv onder elkaar. Kan je dat uitzetten?

2022-03-21 15:36 UTC, MartijnAmbagtsheer commented on app/Models/Section.php
> +  protected $fillable = ['questionnaire_id', 'geofence_id', 'title', 'description', 'location'];
`/* @var array */`

2022-03-21 15:38 UTC, MartijnAmbagtsheer commented on config/app.php
> +      */
@GewoonJaap prettier loopt hier ook dingen aan te passen die niet hoeven

2022-03-21 16:28 UTC, GewoonJaap commented on config/app.php
> +      */
Ja doet ie gewoon standaard, opzich niet heel erg lijkt me? Alles in dezelfde code style en gebeurt maar 1 keer, hierna zitten we er nooit meer aan gok ik

2022-03-21 16:40 UTC, GewoonJaap commented on app/Models/Answer.php
> +  protected $fillable = ['participant_id', 'question_option_id', 'answer'];
Gefixt

2022-03-21 17:29 UTC, GewoonJaap approved these changes

2022-03-21 19:51 UTC, MartijnAmbagtsheer requested changes
Ik mis (nog steeds) factories (voor het testen) en de database testen

2022-03-21 20:52 UTC, GewoonJaap commented
> Ik mis (nog steeds) factories (voor het testen) en de database testen

Om heel eerlijk te zijn zie ik niet helemaal het nut van het testen van je database modellen. Want wil je eigenlijk testen?

2022-03-22 10:20 UTC, MartijnAmbagtsheer approved these changes

2022-03-22 10:20 UTC, merged