SOF-341 Add API Key
Project-Accessibility/web-portal pull request #34
Opened 2022-04-26 14:49 UTC by GewoonJaap

**Closes #XX**

## Description

Add API key to Docker

## Checklist

- [ ] I have run `yarn format`
- [ ] I have run `php artisan test`
- [ ] This PR does not add any errors to the console

A build will automatically be run by GitHub actions when any changes are made on this PR. This must complete successfully before merging.

## Screenshots or videos

<details>
<summary>Click to expand</summary>

</details>

2022-04-29 06:35 UTC, MartijnAmbagtsheer requested changes

2022-04-29 06:35 UTC, MartijnAmbagtsheer commented on .env.example
> +API_KEY=0800fc577294c34e0b28ad2839435945
Dit is toch niet bedoeld voor in de example?

2022-04-29 06:39 UTC, GewoonJaap commented on .env.example
> +API_KEY=0800fc577294c34e0b28ad2839435945
Jawel anders werkt t niet met docker

2022-05-03 20:00 UTC, MartijnAmbagtsheer approved these changes

2022-05-04 14:31 UTC, milovdpas approved these changes

2022-05-04 14:31 UTC, merged