SOF-299 Participants
Project-Accessibility/web-portal pull request #35
Opened 2022-04-29 12:32 UTC by MartijnAmbagtsheer

**Closes #SOF-299**

## Description

Code generation for participants

## Checklist

- [x] I have run `yarn format`
- [x] I have run `php artisan test`
- [x] This PR does not add any errors to the console

A build will automatically be run by GitHub actions when any changes are made on this PR. This must complete successfully before merging.

2022-04-29 18:50 UTC, milovdpas commented on app/Casts/Base64.php
> +    }
Je geeft veel verschillende parameters mee, alleen gebruik alleen value. Moeten die parameters daar per se staan?

2022-04-29 18:55 UTC, milovdpas commented on app/Casts/DisplayDateTime.php
> +    }
Is dit nodig vanwege de amerikaanse tijdweergave? Want er bestaat al een cast voor datetime. https://laravel.com/docs/9.x/eloquent-mutators#date-casting

2022-04-29 19:02 UTC, milovdpas commented on routes/auth.php
> -    ])->name('password.update');
Waarom zijn deze uitgecomment?

2022-04-29 19:09 UTC, GewoonJaap requested changes

2022-04-29 19:09 UTC, GewoonJaap commented on app/Casts/Base64.php
> +class Base64 implements CastsAttributes
Dit gingen we niet meer gebruiken toch voor de codes?

2022-05-02 12:12 UTC, MartijnAmbagtsheer commented on app/Casts/DisplayDateTime.php
> +    }
Dit wil je niet altijd en dan kan ik niet werken met woorden zoals 'om' etc

2022-05-02 12:12 UTC, MartijnAmbagtsheer commented on routes/auth.php
> -    ])->name('password.update');
Worden niet gebruikt dus overbodig.

2022-05-02 21:31 UTC, milovdpas commented on routes/auth.php
> -    ])->name('password.update');
Willen we dit niet meer in de applicatie hebben zitten, want anders moet dit worden toegevoegd aan Jira als user story

2022-05-03 19:30 UTC, MartijnAmbagtsheer commented on routes/auth.php
> -    ])->name('password.update');
Moet later nog worden toegevoegd ja

2022-05-04 18:08 UTC, milovdpas approved these changes

2022-05-04 20:07 UTC, GewoonJaap approved these changes

2022-05-04 20:07 UTC, merged