SOF-304 question answers
Project-Accessibility/web-portal pull request #36
Opened 2022-04-29 14:27 UTC by milovdpas

**Closes #304**

## Description

Het weergeven van een antwoord en opslaan van een antwoord via de API.

## Review focus

Focus op het weergeven van alle vraag types antwoorden en gebruik deze link om een antwoord te openen. http://127.0.0.1:8000/researches/1/questionnaires/1/sections/1/questions/1/answer/1. 
Als je zelf een antwoord wil aanmaken, gebruik dan deze postman https://documenter.getpostman.com/view/19421222/UyrDCvKS 

## Checklist

- [ ]  php artisan migrate:fresh --seed

A build will automatically be run by GitHub actions when any changes are made on this PR. This must complete successfully before merging.

## Screenshots or videos

![image](https://user-images.githubusercontent.com/63716517/165964291-d7ef3fd5-6ffc-4684-9bd6-8239bfe9362b.png)

2022-05-01 09:02 UTC, GewoonJaap requested changes
Zou je misschien een seeder kunnen toevoegen die een participant erin doet en een answer? 
Ik krijg nu dit: 
![afbeelding](https://user-images.githubusercontent.com/33700526/166139200-00afe43d-910b-4d1f-b9b8-d9ab4e01487f.png)

Weet niet of ik iets fout doe?

2022-05-02 11:49 UTC, milovdpas commented
> Zou je misschien een seeder kunnen toevoegen die een participant erin doet en een answer? Ik krijg nu dit: ![afbeelding](https://user-images.githubusercontent.com/33700526/166139200-00afe43d-910b-4d1f-b9b8-d9ab4e01487f.png)
> 
> Weet niet of ik iets fout doe?

Yes doe ik

2022-05-02 13:25 UTC, GewoonJaap requested changes
![afbeelding](https://user-images.githubusercontent.com/33700526/166241089-671f487d-79f1-4e7e-bce4-b24157a23aaa.png)
Krijg deze error als ik een vraag wilt beantwoorden.

![afbeelding](https://user-images.githubusercontent.com/33700526/166241122-7af37538-cea7-4eae-9fb3-0a03c3470801.png)
Krijg ook deze error

2022-05-02 21:14 UTC, milovdpas commented
> ![afbeelding](https://user-images.githubusercontent.com/33700526/166241089-671f487d-79f1-4e7e-bce4-b24157a23aaa.png) Krijg deze error als ik een vraag wilt beantwoorden.
> 
> ![afbeelding](https://user-images.githubusercontent.com/33700526/166241122-7af37538-cea7-4eae-9fb3-0a03c3470801.png) Krijg ook deze error

1ste error houd in dat dat je participant blijkbaar niet geauthoriseerd is om de vraag te beantwoorden. Voor welke vragenlijst heb je de participant aangemaakt/bestaat de participant wel met die code?

En voor de 2de error, dit is van de pull request van de feature/participants. Dus daar heb ik niks mee te maken.

> ![afbeelding](https://user-images.githubusercontent.com/33700526/166241089-671f487d-79f1-4e7e-bce4-b24157a23aaa.png) Krijg deze error als ik een vraag wilt beantwoorden.
> 
> ![afbeelding](https://user-images.githubusercontent.com/33700526/166241122-7af37538-cea7-4eae-9fb3-0a03c3470801.png) Krijg ook deze error

De 1ste error komt als je participant of niet bij de vragenlijst hoort of als de participant niet bestaat. Heb je gecheckt of dit wel klopt?
De 2de error komt door de rebase met de feature/participants branch, die heb ik nu gefixt.

2022-05-05 16:50 UTC, MartijnAmbagtsheer requested changes

2022-05-05 16:50 UTC, MartijnAmbagtsheer commented on app/Enums/QuestionOptionType.php
> +            QuestionOptionType::VIDEO => "Video's",
```suggestion
            QuestionOptionType::VIDEO => 'Video\'s',
```

Anders krijg je wellicht problemen met het laten zien omdat je zo ook normale strings doet weergeven.

2022-05-07 08:04 UTC, GewoonJaap requested changes
![afbeelding](https://user-images.githubusercontent.com/33700526/167245166-17ce7123-d64c-4a6b-aaff-6a8477f087cc.png)
Krijg deze error wanneer ik mijn antwoord wil inzien

2022-05-10 10:12 UTC, milovdpas commented
> ![afbeelding](https://user-images.githubusercontent.com/33700526/167245166-17ce7123-d64c-4a6b-aaff-6a8477f087cc.png) Krijg deze error wanneer ik mijn antwoord wil inzien

Ligt er waarschijnlijk aan dat de array voor multiple choice niet dit is ["Waarde 1", "Waarde 3"]. Ik ga ff checken of dit zo is en of ik er dan validatie voor moet schrijven.

2022-05-10 14:46 UTC, GewoonJaap approved these changes

2022-05-10 14:46 UTC, merged