SOF-339 - Tabs fixed
Project-Accessibility/web-portal pull request #41
Opened 2022-05-14 20:23 UTC by MartijnAmbagtsheer

**Closes #SOF-339**

## Description

Tabs now abort the request if the query is not in the list of tabs.

## Checklist

- [x] I have run `yarn format`
- [x] I have run `php artisan test`
- [x] This PR does not add any errors to the console

A build will automatically be run by GitHub actions when any changes are made on this PR. This must complete successfully before merging.

2022-05-15 09:25 UTC, GewoonJaap commented on app/View/Components/Tabs.php
> +        abort(Response::HTTP_NOT_FOUND, 'tab not found');
Tab

2022-05-15 09:26 UTC, GewoonJaap requested changes
![Schermafbeelding 2022-05-15 om 11 25 40](https://user-images.githubusercontent.com/33700526/168466042-4a25fc97-c772-4ed5-8953-d0dd9adb10dd.png)
Hoort het dat het scherm er zo uit ziet? Of ziet het er zonder debug mode anders uit? Is dit trouwens de flow die we willen? Wil je niet terug vallen op bv t eerste tabje in de lijst?

2022-05-15 21:16 UTC, MartijnAmbagtsheer commented
@GewoonJaap zonder debug krijg je idd gewoon error pagina inplv stack trace. Ik vind zelf deze flow beter zodat de gebruiker feedback krijgt van zijn handeling inplv alsnog een "goed" resultaat.

2022-05-17 08:30 UTC, MartijnAmbagtsheer commented
http://dashboard.test/researches/1/questionnaires/1?tab=Resultaten

2022-05-19 14:52 UTC, milovdpas approved these changes

2022-05-20 09:55 UTC, GewoonJaap requested changes
![afbeelding](https://user-images.githubusercontent.com/33700526/169503717-356e70d1-3a49-4e8d-aa03-039b0445999e.png)
Vragen zijn niet zichtbaar

2022-05-20 10:59 UTC, GewoonJaap approved these changes

2022-05-20 10:59 UTC, merged