SOF-352 - Modified mutiple choice error handling
Project-Accessibility/web-portal pull request #42
Opened 2022-05-14 20:26 UTC by MartijnAmbagtsheer

**Closes #SOF-352**

## Description

The user gets a error if they have selected the option to add a multiple choice option but has no given options.

## Checklist

- [x] I have run `yarn format`
- [ 
- [x] I have run `php artisan test`
- [x] This PR does not add any errors to the console

A build will automatically be run by GitHub actions when any changes are made on this PR. This must complete successfully before merging.

2022-05-15 09:19 UTC, GewoonJaap requested changes
Als je 1 meerkeuze antwoord hebt krijg je de verkeerde error: `List moet minimaal 2 waardes bevatten.`, list klinkt vreemd

2022-05-15 09:20 UTC, GewoonJaap commented on app/Http/Requests/StoreQuestionRequest.php
> +                'Bij een meerkeuze mogelijkheid zijn minimaal twee mogelijkheden veriest.',
mogelijkheid -> vraag

2022-05-19 07:38 UTC, GewoonJaap commented on app/Http/Requests/StoreQuestionRequest.php
> +                'Bij een meerkeuze vraag zijn minimaal twee mogelijkheden veriest.',
veriest -> vereist

2022-05-19 09:23 UTC, GewoonJaap approved these changes

2022-05-19 13:14 UTC, milovdpas approved these changes

2022-05-19 13:19 UTC, merged