SOF-333 Add delete popup
Project-Accessibility/web-portal pull request #46
Opened 2022-05-19 11:11 UTC by GewoonJaap

**Closes #XX**

## Description

## Review focus

## Checklist

- [ ] I have run `yarn format`
- [ ] I have run `php artisan test`
- [ ] This PR does not add any errors to the console

A build will automatically be run by GitHub actions when any changes are made on this PR. This must complete successfully before merging.

## Screenshots or videos

<details>
<summary>Click to expand</summary>

</details>

2022-05-19 13:55 UTC, MartijnAmbagtsheer commented
![image](https://user-images.githubusercontent.com/63644928/169310640-f97d2759-a223-41e8-901a-4d1af6a217b3.png)

Zorg dat dit minimaal 7

2022-05-19 13:56 UTC, MartijnAmbagtsheer requested changes
Zie comment

2022-05-19 14:33 UTC, milovdpas commented
> ![image](https://user-images.githubusercontent.com/63644928/169310640-f97d2759-a223-41e8-901a-4d1af6a217b3.png)
> 
> Zorg dat dit minimaal 7

En dan de de rode kleur van onze css gebruiken en een donker grijze kleur gebruiken voor de cancel

2022-05-20 12:39 UTC, MartijnAmbagtsheer approved these changes

2022-05-21 14:12 UTC, milovdpas approved these changes

2022-05-21 14:12 UTC, merged