SOF-207: Input component
Project-Accessibility/web-portal pull request #5
Opened 2022-03-21 16:59 UTC by milovdpas

**Closes #XX**

## Description

Made input component

## Review focus

Bootstrap has been deleted, so testing local will not show the correct bootstrap styling.
So focus on the read me and if it's clear how to use the component.

A build will automatically be run by GitHub actions when any changes are made on this PR. This must complete successfully before merging.

2022-03-21 18:17 UTC, wwessel01 approved these changes
Readme is duidelijk en component werkt goed 👍

2022-03-22 10:40 UTC, GewoonJaap commented
Vergeet prettier niet ;)

2022-03-22 12:10 UTC, MartijnAmbagtsheer requested changes

2022-03-22 12:10 UTC, MartijnAmbagtsheer commented on README.md
> +    $extraData=(object)array(
Hoezo maken we hier een object van? Array is goed genoeg toch?

2022-03-22 12:10 UTC, MartijnAmbagtsheer commented on README.md
> +        "options" => array("optie1", "optie2", "optie3"),
Is het geen idee om dit te hebben?

```
$extraData = [
  ['option_1', 'value_1'],
  ['option_2', 'value_2'],
];
```

2022-03-22 12:10 UTC, MartijnAmbagtsheer commented on README.md
> +@php
Zit te twijfelen of ik dit wel in de view wil hebben of dat we dit via de controller regelen en aan de view meegeven. Ik vind ruwe phpcode in de view niet zo netjes...

2022-03-22 12:19 UTC, IntissarJ requested changes
Voor de rest ziet het er wel goed uit alleen dat er hier naar gekeken wrd. Goed bezig

2022-03-22 12:19 UTC, IntissarJ commented on resources/views/welcome.blade.php
> +    <style>
Is het niet beter styling op aparte bestand te zetten, Volgens mij niet de bedoeling het in de blade te hebben op deze manier

2022-03-22 12:21 UTC, IntissarJ commented
Vergeet ook niet prettier te runnen nadat je klaar bent met coderen, vanwege formatting

2022-03-22 12:25 UTC, MartijnAmbagtsheer commented on resources/views/welcome.blade.php
> +    <style>
Dit gaat er uit in mijn MR.

Dit heeft ermee te maken dat bootstrap nog geconfigureerd moet worden met de juiste styling. Kan voor nu ermee door

2022-03-22 12:29 UTC, MartijnAmbagtsheer commented on README.md
> +        "min" => 0,
Single quotes gebruiken. Maakt je website wat sneller en houd het consistent als je bijv dit gebruikt

`$string = 'Martijn zei gisteren: "Hallo"';`

2022-03-22 14:54 UTC, milovdpas commented on README.md
> +    $extraData=(object)array(
Object is beter, omdat het ook gebruikt wordt in andere inputs behalve select. Bijvoorbeeld bij de switch, dan heb je drie variabelen ik vindt het dan persoonlijk netter om het in een object te zetten.

2022-03-22 14:59 UTC, milovdpas commented on README.md
> +    $extraData=(object)array(
Ik bedenk me, array kan idd prima. Dan wordt het bij switch ```["step" => 0.5, "min" => 0, "max"=>5]

2022-03-23 21:14 UTC, MartijnAmbagtsheer requested changes

2022-03-24 09:50 UTC, MartijnAmbagtsheer requested changes

2022-03-24 09:50 UTC, MartijnAmbagtsheer commented on resources/views/components/input.blade.php
> +            @foreach($extraData["options"] as $option)
Wat ik hierbij nog zou willen zien is dat je ook kan meegeven bij een option of deze is geselecteerd. Beter voor de UX

2022-03-24 09:50 UTC, MartijnAmbagtsheer commented on resources/views/components/input.blade.php
> +                @if(($index == 0 && empty($value))||$value==$option[1])
Dus of op basis van eerste of op basis van eentje die is geselecteerd.

2022-03-24 10:14 UTC, milovdpas commented on resources/views/components/input.blade.php
> +                @if(($index == 0 && empty($value))||$value==$option[1])
Ja

2022-03-24 10:14 UTC, milovdpas commented on resources/views/components/input.blade.php
> +            @foreach($extraData["options"] as $option)
Dan geef je de value mee

2022-03-24 10:16 UTC, MartijnAmbagtsheer approved these changes

2022-03-24 10:16 UTC, merged