Feature/SOF-203 button component
Project-Accessibility/web-portal pull request #6
Opened 2022-03-21 19:42 UTC by milovdpas

**Closes #SOF-203**

## Description

Made Button component

## Review focus

Bootstrap has been deleted, so testing local will not show the correct bootstrap styling.
So focus on the read me and if it's clear how to use the component.

A build will automatically be run by GitHub actions when any changes are made on this PR. This must complete successfully before merging.

2022-03-21 20:46 UTC, GewoonJaap approved these changes

2022-03-22 10:40 UTC, GewoonJaap commented
Vergeet prettier niet ;)

2022-03-22 12:20 UTC, MartijnAmbagtsheer commented on README.md
> +Verschillende types zijn: primary, seocndary en remove.\
Opzich zou naast een `remove` een `add` ook wel mooi zijn met de klasse `btn-success`

2022-03-22 12:21 UTC, MartijnAmbagtsheer requested changes

2022-03-22 12:21 UTC, MartijnAmbagtsheer commented on resources/views/components/button.blade.php
> +    <button type="submit"
Is het altijd een submit of zou dat misschien ook een type kunnen zijn?

2022-03-22 15:35 UTC, milovdpas commented on README.md
> +Verschillende types zijn: primary, seocndary en remove.\
Yes is goed.

2022-03-22 15:37 UTC, milovdpas commented on resources/views/components/button.blade.php
> +    <button type="submit"
Button is altijd of een link of een submit knop. Ik zie niet andere functionaliteiten in van een button. Voor zoeken en filteren is gwn een link met query params bijvoorbeeld.

2022-03-24 09:45 UTC, MartijnAmbagtsheer commented on resources/views/components/button.blade.php
> +    <button type="submit"
En bijv de buttons in de tables? Dat is een link, maar dan in een knop vorm...

2022-03-24 09:47 UTC, MartijnAmbagtsheer requested changes

2022-03-24 09:47 UTC, MartijnAmbagtsheer commented on resources/views/components/button.blade.php
> +            @break
Je tabs lopen hier niet helemaal lekker

2022-03-24 09:47 UTC, MartijnAmbagtsheer commented on resources/views/welcome.blade.php
> +                                    <x-button class="mx-4" type="primary" link="https://www.google.com">Press me</x-button>
Zodra dit is gemerged neem ik hem mee in mijn stylesheet.

2022-03-24 10:14 UTC, MartijnAmbagtsheer approved these changes

2022-03-24 12:40 UTC, merged