fix range answer
Project-Accessibility/web-portal pull request #60
Opened 2022-05-26 16:23 UTC by milovdpas

2022-05-27 07:48 UTC, MartijnAmbagtsheer approved these changes

2022-05-27 18:08 UTC, GewoonJaap commented on app/Http/Controllers/Api/QuestionController.php
> +                if (!$request->get('IMAGE')) {
Klopt dit?

2022-05-27 18:08 UTC, GewoonJaap commented on app/Http/Controllers/Api/QuestionController.php
> +                if (!$request->get('IMAGE')) {
Omdat het eerst over een image gaat en dan in die IF de voice

2022-05-28 10:25 UTC, GewoonJaap requested changes
Image/voice submit lijkt niet meer te werken icm de app. Slider werkt wel gewoon. Is die image/voice rewrite nodig? Anders zou ik t weglaten, eerst werkte die 2 wel

2022-05-28 12:58 UTC, milovdpas commented on app/Http/Controllers/Api/QuestionController.php
> +                if (!$request->get('IMAGE')) {
> 

Klopt ik zei gister ook dat het nog niet werkte, nu zou het wel moeten werken

2022-05-28 12:58 UTC, milovdpas commented
> Image/voice submit lijkt niet meer te werken icm de app. Slider werkt wel gewoon. Is die image/voice rewrite nodig? Anders zou ik t weglaten, eerst werkte die 2 wel

Klopt ik zei gister ook dat het nog niet werkte, nu zou het wel moeten werken

2022-05-28 12:59 UTC, milovdpas commented on app/Http/Controllers/Api/QuestionController.php
> +                if (!$request->get('IMAGE')) {
Deze is idd aangepast

2022-05-30 10:26 UTC, wwessel01 approved these changes

2022-05-30 10:27 UTC, GewoonJaap approved these changes

2022-05-30 10:27 UTC, merged