change full size popup of video's and images
Project-Accessibility/web-portal pull request #64
Opened 2022-06-02 19:43 UTC by milovdpas

## Description

Video en afbeelding antwoord "volle grote" styling goed maken

2022-06-03 07:10 UTC, GewoonJaap approved these changes

2022-06-03 11:57 UTC, MartijnAmbagtsheer requested changes

2022-06-03 11:57 UTC, MartijnAmbagtsheer commented on resources/views/admin/question/answer.blade.php
> +                                        aria-labelledby="image {{$loop->index}} modal"
Graag in het Nederlands omdat de website ook op het Nederlands staat en onze content in het Nederlands is

2022-06-03 11:57 UTC, MartijnAmbagtsheer commented on resources/views/admin/question/answer.blade.php
> +                                        <div class="modal-dialog modal-dialog-centered p-0">
`.modal-xl` toevoegen. Heb je net wat meer ruimte en kan de afbeelding ook meer worden vergroot.

2022-06-03 11:57 UTC, MartijnAmbagtsheer commented on resources/views/admin/question/answer.blade.php
> +                                @foreach($answer->values as $link)
Niet voor elk plaatje een nieuwe modal. Je kan content meegeven. Zo kan je dus de image url meegeven en heb je maar 1 image nodig. Scheelt weer in rendertijd van de pagina.

Docs: https://getbootstrap.com/docs/5.0/components/modal/#varying-modal-content

2022-06-03 11:57 UTC, MartijnAmbagtsheer commented on resources/views/admin/question/answer.blade.php
> +                                                    <button type="button" class="btn btn-secondary"
Veron wilde graag optie 2 van de opties die je had gestuurd en dat was degene met `btn-primary`

![image](https://user-images.githubusercontent.com/63644928/171848544-f283a3f6-efc7-4435-8bfc-86bd931b85e5.png)
![image](https://user-images.githubusercontent.com/63644928/171848575-6c17bf78-bf82-4f25-bc85-c274e2644202.png)

2022-06-03 11:57 UTC, MartijnAmbagtsheer commented on resources/views/admin/question/answer.blade.php
> +                        <section id="images">
videos

2022-06-03 11:57 UTC, MartijnAmbagtsheer commented on resources/views/admin/question/answer.blade.php
> +                            @foreach($answer->values as $link)
Ook hiervoor dezelfde comments als bij de `image`

2022-06-03 20:36 UTC, milovdpas commented on resources/views/admin/question/answer.blade.php
> +                                        <div class="modal-dialog modal-dialog-centered p-0">
Niet waar, want de verhouding van de afbeelding moet worden behouden.

2022-06-03 20:41 UTC, milovdpas commented on resources/views/admin/question/answer.blade.php
> +                                @foreach($answer->values as $link)
Martijn, ik denk dat het te veel gedoe is voor de video en dat het niet echt de performance van de pagina zal beinvloeden. Dus ik laat het denk het gewoon zo als je dat niet erg vindt.

2022-06-03 20:44 UTC, milovdpas commented on resources/views/admin/question/answer.blade.php
> +                                        <div class="modal-dialog modal-dialog-centered p-0">
max height van de modal is 75vh

2022-06-06 08:36 UTC, MartijnAmbagtsheer commented on resources/views/admin/question/answer.blade.php
> +                                        <div class="modal-dialog modal-dialog-centered p-0">
Hoezo 'maar' 75vh? Is dat standaard bootstrap?

2022-06-06 08:44 UTC, MartijnAmbagtsheer commented on resources/views/admin/question/answer.blade.php
> +                                @foreach($answer->values as $link)
Liever niet, maar door tijdgebrek prima. Ik heb een kaartje gemaakt voor eventuele optimalisatie. Als straks participanten 5 afbeeldingen en 5 video's kunnen opsturen wordt echt wel een dingetje....

2022-06-06 12:25 UTC, milovdpas commented on resources/views/admin/question/answer.blade.php
> +                                        <div class="modal-dialog modal-dialog-centered p-0">
custom, dit was heel het doel van deze PR. Dat de image dus te groot werd en dus niet pasde op het scherm, daarom is de height standaard 75vh gemaakt.

2022-06-06 12:26 UTC, milovdpas commented on resources/views/admin/question/answer.blade.php
> +                                @foreach($answer->values as $link)
Dat bedoel ik ook ja, tijdsgebrek het is belangrijk dat we eerst de echte bugs fixen. En dat pas deze optimalisaties gaan doen anders blijven we echt te veel hangen

2022-06-06 12:27 UTC, MartijnAmbagtsheer approved these changes

2022-06-06 12:29 UTC, merged