fix bug in removeAnswers function and remove file if isn't used
Project-Accessibility/web-portal pull request #65
Opened 2022-06-02 20:32 UTC by milovdpas

**Closes #429**

## Description

Check of het opslaan van antwoorden lukt en of de files in de storage worden verwijderd als ze worden vervangen

2022-06-03 07:14 UTC, GewoonJaap requested changes
Krijg dit bericht op okteto ``	"message": "unlink(\/app\/storage\/app\/public\/https:\/\/laravel-pr-65-gewoonjaap.cloud.okteto.net\/storage\/upload\/files\/videos\/20220603_6299b49494004.mp4): No such file or directory"`` 

Denk dat dit: `https:\/\/laravel-pr-65-gewoonjaap.cloud.okteto.net\/storage\/upload` niet nodig is?

2022-06-03 11:59 UTC, MartijnAmbagtsheer commented on app/Http/Controllers/Api/QuestionController.php
> +                    'app/public/' . str_replace($search, '', $filePath),
`asset()` is beter. Dit haalt automatisch de juiste url van der server op en linkt deze naar de juiste folter.

2022-06-03 18:55 UTC, milovdpas commented on app/Http/Controllers/Api/QuestionController.php
> +                    'app/public/' . str_replace($search, '', $filePath),
Je moet de file in de storage verwijderen niet de publieke file path krijgen

2022-06-03 18:57 UTC, milovdpas commented
> APP_URL

Klopt dan staat dus de APP_URL niet ingesteld. das wel kut, want die moeten we per environment configureren.

2022-06-03 19:10 UTC, milovdpas commented
> Krijg dit bericht op okteto ` "message": "unlink(\/app\/storage\/app\/public\/https:\/\/laravel-pr-65-gewoonjaap.cloud.okteto.net\/storage\/upload\/files\/videos\/20220603_6299b49494004.mp4): No such file or directory"`
> 
> Denk dat dit: `https:\/\/laravel-pr-65-gewoonjaap.cloud.okteto.net\/storage\/upload` niet nodig is?

gefixt

2022-06-06 08:33 UTC, MartijnAmbagtsheer approved these changes

2022-06-08 12:28 UTC, GewoonJaap approved these changes

2022-06-08 12:28 UTC, merged