you can now only get questionnaire if is open
Project-Accessibility/web-portal pull request #69
Opened 2022-06-03 15:56 UTC by milovdpas

**Closes #XX**

## Description

you can now only get questionnaire if is open

## Review focus

Test of de endpoint "{url}/api/questionnaires/VKHOG" alleen de vragenlijst teruggeeft als de vragenlijst open staat.

2022-06-03 16:46 UTC, MartijnAmbagtsheer requested changes

2022-06-03 16:46 UTC, MartijnAmbagtsheer commented on app/Http/Requests/GetQuestionnaireRequest.php
> +            )->first();
```suggestion
            )->firstOrFail();
```

2022-06-03 17:00 UTC, GewoonJaap commented on app/Http/Requests/GetQuestionnaireRequest.php
> +            if ($participant && !$participant->questionnaire->open) {
Crasht dit niet als je een ongeldige code invoert?

2022-06-03 18:46 UTC, milovdpas commented on app/Http/Requests/GetQuestionnaireRequest.php
> +            )->first();
Wordt al gedaan in de controller

2022-06-03 18:47 UTC, milovdpas commented on app/Http/Requests/GetQuestionnaireRequest.php
> +            if ($participant && !$participant->questionnaire->open) {
Ja tenzij je first or fail gebruikt. Alleen die wordt al gebruikt in de controller

2022-06-04 08:37 UTC, MartijnAmbagtsheer commented on app/Http/Requests/GetQuestionnaireRequest.php
> +            if ($participant && !$participant->questionnaire->open) {
Waarom zou je het niet al bij de validatie tegenhouden?

2022-06-04 08:38 UTC, MartijnAmbagtsheer commented on app/Http/Requests/GetQuestionnaireRequest.php
> +            )->first();
Klopt, maar dit komt als eerste toch? Zou het zelfs uit de controller gehaald kunnen worden.

2022-06-05 12:10 UTC, GewoonJaap approved these changes

2022-06-06 08:34 UTC, MartijnAmbagtsheer approved these changes

2022-06-06 08:34 UTC, merged