SOF-398
Project-Accessibility/web-portal pull request #72
Opened 2022-06-07 11:55 UTC by MartijnAmbagtsheer

**Closes #SOF-398**

## Description

The API has now a function to close a questionnaire for a participant.

## Review focus

**If the participant is already finished, you'll get a 403 resposne**

## Checklist

- [x] I have run `yarn format`
- [x] I have run `php artisan test`
- [x] This PR does not add any errors to the console

A build will automatically be run by GitHub actions when any changes are made on this PR. This must complete successfully before merging.

2022-06-07 12:42 UTC, Darkshadenl approved these changes
Nice stuff.

2022-06-07 17:38 UTC, GewoonJaap commented on app/Http/Controllers/Api/QuestionnaireController.php
> +        $participant->save();
Zorgt dit er ook voor dat je nu geen questions meer kan submitten?

2022-06-07 22:39 UTC, milovdpas requested changes

2022-06-07 22:39 UTC, milovdpas commented on app/Http/Controllers/Api/QuestionnaireController.php
> +        $participant->save();
Zoals Jaap al zegt, de participant kan nu nog steeds de questionnaire ophalen en antwoorden submitten. Dit moet nog afgebakend worden.

2022-06-09 19:45 UTC, milovdpas requested changes

2022-06-09 19:45 UTC, milovdpas commented on app/Http/Controllers/Api/QuestionController.php
> +        $participant = Participant::whereCode($code)->whereFinished(false)->firstOrFail();
In de authorize van de StoreAnswerRequest zetten

2022-06-09 19:45 UTC, milovdpas commented on app/Http/Controllers/Api/QuestionnaireController.php
> +        $participant = Participant::whereCode($code)->whereFinished(false)->firstOrFail();
In validator doen

2022-06-09 19:45 UTC, milovdpas commented on app/Http/Controllers/Api/QuestionController.php
> +        $participant = Participant::whereCode($code)->whereFinished(false)->firstOrFail();
Maakt me niet heel veel uit trouwens, alleen dit moest ik ook doen bij de GetQuestionnaireRequest. Dus voor consistentie dan ook maar hier doen.

2022-06-14 19:25 UTC, milovdpas approved these changes

2022-06-14 19:27 UTC, GewoonJaap approved these changes

2022-06-14 19:31 UTC, merged