SOF-421 - Correct date and time for the participants overview
Project-Accessibility/web-portal pull request #74
Opened 2022-06-09 19:33 UTC by MartijnAmbagtsheer

**Closes #SOF-421**

## Description

The correct date and time is now shown on the participants overview.

## Checklist

- [x] I have run `yarn format`
- [x] I have run `php artisan test`
- [x] This PR does not add any errors to the console

A build will automatically be run by GitHub actions when any changes are made on this PR. This must complete successfully before merging.

## Screenshots or videos

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/63644928/172929709-1c18b202-055b-4a8c-be6e-bd3ea13cfd34.png)

</details>

2022-06-13 14:05 UTC, Darkshadenl requested changes
Ik krijg in de online omgeving een 500 error als ik naar participants ga.

2022-06-15 10:32 UTC, milovdpas approved these changes
Tijden worden goed weergegeven en participant view geeft geen 500 error meer

2022-06-15 10:32 UTC, milovdpas requested changes
Aan de Readme nieuwe manier van breadcrumbs uitleggen

2022-06-15 11:24 UTC, milovdpas approved these changes

2022-06-15 11:25 UTC, GewoonJaap approved these changes

2022-06-15 12:57 UTC, merged